name: ARC Testd

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: github-arc-runners
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Hello from ARC runner on OpenShift TUdor 2025"
          uname -a
